### ISSUE TITLE
Kalender en time forud

### ISSUE THREAD

**Issue by TheColorman** [soeren-b-c/lectio-skema-til-.ics-kalender#11]
Når jeg downloader kalenderen og indsætter den, er alle modulerne en time forud. (F.eks. i stedet for at starte 8:15, starter de 9:15). Min servers tidszone er UTC+00, men systemtiden er manuelt ændret til Dansk tid.

**Comment by soeren-b-c** [comment]
Min mavefornemmelse er at det er ændringen af systemtiden der driller, men det er kun et gæt.
Hvordan har du ændret systemtiden?

Hvad er det for en server distribution?

Jeg har ikke tid til at kigge på det lige nu, men vil gerne teste efter selv, når jeg får lidt tid - måske i uge 7.

**Comment by TheColorman** [comment]
Jeg brugte `timedatectl set-time [tiden på min telefon]`, fordi der kun var 1 tidszone da jeg brugte `timedatectl list-timezones`

**Comment by soeren-b-c** [comment]
Må jeg ikke lige se output af
`timedatectl `

**Comment by TheColorman** [comment]
`timedatectl`
```
Local time: Thu 2020-01-30 15:47:24 UTC

Universal time: Thu 2020-01-30 15:47:24 UTC

RTC time: Thu 2020-01-30 15:47:25
Time zone: n/a (UTC, +0000)

System clock synchronized: yes

NTP service: inactive

RTC in local TZ: no
```

**Comment by soeren-b-c** [comment]
Kan jeg ikke lokke dig til at prøve at sætte uret en time tilbage (altså så det faktisk er sat til korrekt UTC), og så prøve om kalenderen stadig angiver den forkerte tid?

At der ikke er nogen tidszoner at vælge imellem lyder mystisk. Jeg vil gerne forsøge at hjælpe dig med det, men så skal du lige give lidt mere info om dit system. Hvilken distribution, version osv...

**Comment by TheColorman** [comment]
Jeg skiftede tiden tilbage til UTC+0000 lokaltid, men det ændrede ikke noget. Jeg tjekkede selve .ics filen, og der var tiden rigtig nok med den rigtige tidszone (dansk).

Jeg køre Ubuntu Minimal 19.10 Eoan Ermine som køre på en Google Cloud server.

**Comment by soeren-b-c** [comment]
Hej igen, du må undskylde der er gået så lang tid før jeg har fået svaret dig...

Jeg er usikker på dit svar, så nu spørger jeg lige for at være helt sikker.

Er det rigtigt at du har sat din tidszone tilbage således at "Universal time" faktisk er en time bagefter vores DK tid? Så UTC på dit system er sat korrekt?

Og så har du stoppet node-scriptet, startet det igen, hentet kalenderen, og tiderne i kalenderen er stadig ikke rigtige, men en time forskudt?

Er det rigtigt forstået?
