### ISSUE TITLE
Sommertid/vintertid

### ISSUE THREAD

**Issue by BjornGrylls** [soeren-b-c/lectio-skema-til-.ics-kalender#18]
Hvis ikke jeg tager fejl, så kan den ikke finde ud af at det er vintertid næste uge.

![image](https://user-images.githubusercontent.com/35100000/96858105-1ebc3980-1460-11eb-975e-7af15a40f478.png)

**Comment by soeren-b-c** [comment]
Hejsa

Jeg har ikke selv haft samme problem. Er du sikker på det er et problem med scriptet, og ikke f.eks. kalenderens fortolkning af data i .ics filen?

Er din Google-kalender sat til tidszone CET / Danmark?

**Comment by BjornGrylls** [comment]
Første event i .ics-filen:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-lectio2ics-service.herokuapp.com/?skole=575&elev=43439479846
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-PUBLISHED-TTL:PT15M
X-WR-CALNAME:Lectio skema
X-WR-TIMEZONE:Europe/Copenhagen
BEGIN:VEVENT
UID:f123ebcea7c75b0b1e61d04317c8590e@lectio2ics-service.herokuapp.com
SEQUENCE:1014392
DTSTAMP:20201025T211116Z
LAST-MODIFIED:20201025T210000Z
DTSTART:20201102T060000Z
DTEND:20201102T064500Z
SUMMARY:Embedded ct. I - dteux3h17XNpro - jwha
END:VEVENT

Tidszonen er Danmark, vintertid. Dvs. +1. I går var den +2.
![image](https://user-images.githubusercontent.com/35100000/97119316-abd8ea00-170f-11eb-922b-ec0f714b6f03.png)
Første lektion starter ifølge .ics kl. 6:00, hvilket burde være kl. 8:00, altså en forskel på +2. Når tidsonen er vintertid vil den kun give +1 og vi ender på kl. 7:00.

**Comment by BjornGrylls** [comment]
Jeg implementerede dette i variablen "skew" 
https://stackoverflow.com/questions/11887934/how-to-check-if-dst-daylight-saving-time-is-in-effect-and-if-so-the-offset/13365722
