### ISSUE TITLE
problemer med start

### ISSUE THREAD

**Issue by EmmiPigen** [soeren-b-c/lectio-skema-til-.ics-kalender#20]
når jeg bruger commandoen "npm start" får jeg dette output. men kan ikke helt tyde hvad det betyder. nogle der kan hjælpe 

node-lectio@1.2.0 start C:\Users\emili\OneDrive - mercantec\lectio-skema-til-.ics-kalender-master
> NODE_ENV=production node -r reify node-lectio.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-lectio@1.2.0 start: `NODE_ENV=production node -r reify node-lectio.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-lectio@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\emili\AppData\Roaming\npm-cache\_logs\2020-10-28T17_57_37_570Z-debug.log

**Comment by soeren-b-c** [comment]
Hejsa

Jeg har ikke erfaring med at køre scriptet under Windows, men en hurtig google-søgning bringer denne side frem:
https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman/48966524
hvor specielt dette svar ser spændende ud:
https://stackoverflow.com/a/40967643

Måske du kan bruge det?

**Comment by EmmiPigen** [comment]
det hjalp, tak for hjælpen
