### ISSUE TITLE
Elev- og lærerID

### ISSUE THREAD

**Issue by TobiasABay** [soeren-b-c/lectio-skema-til-.ics-kalender#21]
Hej, linksene til skolen, eleven samt læreren ID virker ikke, og siger dermed en fejl er opstået

**Comment by soeren-b-c** [comment]
Hejsa

Kan du være lidt mere konkret om hvor det er disse links ikke virker?
Er det links her på github? Eller er det når du kører scriptet?

Vedhæft gerne et screenshot og/eller output fra din terminal, hvor den præcise fejlmeddelelse kan ses.

**Comment by TobiasABay** [comment]
Hej Søren. Tak for dit hurtige svar 😊
Jeg går i 3.g på Midtbyens Gymnasium, og jeg har netop lige påbegyndt vores eksamensprojekt i Teknikfag. Dermed vil jeg lave en discord bot, som bruger jeres API.

Jeg fandt din GitHub, og prøvede at finde mit ELEV ID, dog uden held.
Jeg har vedhæftet en fil, hvor du kan se hvad der stod, når man klikker på linket: https://www.lectio.dk/lectio/SKOLE-ID/SkemaNy.aspx?type=elev&elevid=ELEV-ID

Hilsen Tobias

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

Fra: Søren Bredlund Caspersen<mailto:notifications@github.com>
Sendt: 2. marts 2021 23:13
Til: soeren-b-c/lectio-skema-til-.ics-kalender<mailto:lectio-skema-til-.ics-kalender@noreply.github.com>
Cc: Tobias_bay<mailto:hammer100@hotmail.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [soeren-b-c/lectio-skema-til-.ics-kalender] Elev- og lærerID (#21)


Hejsa

Kan du være lidt mere konkret om hvor det er disse links ikke virker?
Er det links her på github? Eller er det når du kører scriptet?

Vedhæft gerne et screenshot og/eller output fra din terminal, hvor den præcise fejlmeddelelse kan ses.

**Comment by soeren-b-c** [comment]
Hej Tobias

Det lyder spændende :)

Jeg kan ikke se din vedhæftning :(

Bemærk også at det jo ikke er en offentlig API, da der kræves et Lectio-login.
Afhængigt af din tekniske snilde kan det være en fin mulighed at køre en server med scriptet selv. Så styrer du selv hvad der skal ske - specielt hvis du får brug for at lave fejlsøgning når du skal lave din bot.

**Comment by TobiasABay** [comment]
[cid:image003.png@01D7101E.AA9F0310]
Hej, du burde nu kunne se, hvordan fejlen ser ud, når jeg klikker på linket under på 4 på GitHub. Jeg kender SKOLE-ID, men ikke min egen ID

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

Fra: Søren Bredlund Caspersen<mailto:notifications@github.com>
Sendt: 3. marts 2021 10:04
Til: soeren-b-c/lectio-skema-til-.ics-kalender<mailto:lectio-skema-til-.ics-kalender@noreply.github.com>
Cc: Tobias_bay<mailto:hammer100@hotmail.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [soeren-b-c/lectio-skema-til-.ics-kalender] Elev- og lærerID (#21)


Hej Tobias

Det lyder spændende :)

Jeg kan ikke se din vedhæftning :(

Bemærk også at det jo ikke er en offentlig API, da der kræves et Lectio-login.
Afhængigt af din tekniske snilde kan det være en fin mulighed at køre en server med scriptet selv. Så styrer du selv hvad der skal ske - specielt hvis du får brug for at lave fejlsøgning når du skal lave din bot.

**Comment by soeren-b-c** [comment]
Men de links i guiden er blot skabeloner. De virker ikke, før du selv udfylder ID'erne.

Hvis du besøger dit eget skema på Lectio gennem en browser, så prøv at kopiere http-adressen.
Den har samme form som linket i punkt 4, og så kan du aflæse dit id, og skole-id.

**Comment by TobiasABay** [comment]
Det i orden – jeg prøver lige igen
Er du frisk på at hjælpe, hvis jeg oplever problemer?
Botton er programmeret i Javascript med visualstudio og køre ved hjælp af node

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

Fra: Søren Bredlund Caspersen<mailto:notifications@github.com>
Sendt: 3. marts 2021 11:54
Til: soeren-b-c/lectio-skema-til-.ics-kalender<mailto:lectio-skema-til-.ics-kalender@noreply.github.com>
Cc: Tobias_bay<mailto:hammer100@hotmail.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [soeren-b-c/lectio-skema-til-.ics-kalender] Elev- og lærerID (#21)


Men de links i guiden er blot skabeloner. De virker ikke, før du selv udfylder ID'erne.

Hvis du besøger dit eget skema på Lectio gennem en browser, så prøv at kopiere http-adressen.
Den har samme form som linket i punkt 4, og så kan du aflæse dit id, og skole-id.

**Comment by soeren-b-c** [comment]
Jeg hjælper gerne hvis jeg kan. Skriv til mig på soeren.b.c @ gmail.com

:)
