### ISSUE TITLE
Error: Failed to launch the broser process! Raspberry Pi

### ISSUE THREAD

**Issue by Ghitafjorback** [soeren-b-c/lectio-skema-til-.ics-kalender#24]
Hej, 
Først vil jeg bare sig tak, og fedt med dette projekt! Jeg forsøger at hjælpe min nevø med at få hans lectio skema over på hans mobil-kalender.
Jeg har fulgt installationsguiden og alt gik igennem smooth... ja, altså lige bortset fra da jeg skulle ændre detaljerne i filen... det bøvlede jeg lidt med, men endte med at løse det ved at skifte "," ud med ";"... det må være noget regionsbestemt.
Anyways, når jeg følger linket for at få dannet min ics-fil, så får jeg følgende fejl... Den bliver ved at sige, at hans skole-id ikke eksisterer, men det gør det jo.... 
linket ved lectio læser "https://www.lectio.dk/lectio/256/SkemaNy.aspx?type=elev&elevid=########" ergo må 256 være hans skole-id.

jeg starter programmet og følger linket og får nedenstående:
![image](https://user-images.githubusercontent.com/59295827/208252107-f642bcec-6efa-46bf-8881-2a28f1236aa9.png)

men så får jeg denne fejl.
![image](https://user-images.githubusercontent.com/59295827/208251460-1d763851-0fbb-4f3f-9819-fd1f31deea38.png)

Min fil ser sådan her ud
![image](https://user-images.githubusercontent.com/59295827/208251600-e8583fdf-3336-47b2-9b7a-fa22d633099e.png)

Jeg bruger en Raspberry Pi hvis det har nogen betydning.
Har du nogen idé om hvad dette skyldes?
På forhånd mange tak for hjælpen
Mvh Ghita

**Comment by soeren-b-c** [comment]
Hej Ghita,
og velbekomme.

Min mavefornemmelse siger mig at problemet stammer fra din brug af semikolon i stedet for komma i `db.csv` filen.

Vil du ikke prøve at ændre det tilbage igen - og hvis det giver nogle problemer, så beskriv hvad de problemer er så præcist som muligt.
Skriv også gerne hvilket program (hvilken editor) du bruger til at redigere i `db.csv` filen.


Mvh.
Søren

**Comment by Ghitafjorback** [comment]
Hej Søren
Jeg retter direkte i terminalen vha. "vi" funktionen... Nu har jeg rettet tilbage til "," og får igen problemer. Se nedenfor...
![image](https://user-images.githubusercontent.com/59295827/208267647-df0c881c-d52b-41bc-b4ed-d47f8a9261f6.png)

Denne fejl kører bare i ring og ring

**Comment by Ghitafjorback** [comment]
Jeg har nu prøvet at sætte single quotes ' om værdierne i csv-filen, og nu får jeg samme fejl med at "no school matchin id 256"..
Men min csv fil er nu komma-separeret
jeg har prøvet både med og uden single quotes omkring skole-id'et.... den giver samme fejl uanset, men hvis ikke jeg har single quotes omkring mine tekstværdier, men med single quotes går den igennem som sagt, bare med samme fejl igen med at skole-id'et ikke eksisterer

**Comment by soeren-b-c** [comment]
Hej igen

Det er **ikke** csv filen der er problemet. Den skal være med kommaer, og uden quotes, semikolon eller tilsvarende.

Problemet er at chromium (chrome browser) driller på Raspberry Pi.

Jeg har ikke lige mulighed for at tjekke efter her, men en løsning burde være at:

1. Installere chromium (hvis du ikke allerede har den installeret)
    ```sudo apt-get install chromium-browser```

2. Rette omkring linje 52 i browser.js https://github.com/soeren-b-c/lectio-skema-til-.ics-kalender/blob/4de60c63aeb9f13c0adc201f97a0408a8904b4af/browser.js#L52 så du får tilføjet `executablePath`
  Det kan se således ud (men jeg har som sagt ikke dobbelt-tjekket syntaksen om det virker)
```
        ],
        headless: IS_HEADLESS,
        executablePath: '/usr/bin/chromium-browser',
      });
```

Se evt. bug-report hos puppeteer her: https://github.com/puppeteer/puppeteer/issues/550#issuecomment-635718872

**Comment by soeren-b-c** [comment]
Hejsa.

Jeg håber at intet nyt er godt nyt, og jeg tillader mig at lukke dette issue her til aften.

Skriv endelige igen hvis problemet ikke er løst, eller hvis der dukker nye problemer op.
Mvh.
Søren
