### ISSUE TITLE
No school matching id

### ISSUE THREAD

**Issue by EsbenRun** [soeren-b-c/lectio-skema-til-.ics-kalender#26]
Jeg bliver ved med at få fejlen `No school matching id 165`, og jeg har prøvet at kigge lidt i koden for at se om jeg havde sat noget forkert op, og kunne umiddelbart ikke finde nogle problemer, tænkte om det var et kendt problem eller om det kun er mig? 
Min skoles id er 165 og jeg kører koden på Kali Linux.

**Comment by soeren-b-c** [comment]
Har du husket at oprette db.csv og indskrive brugernavn og adgangskode?

Det ville være mit første gæt.

**Comment by EsbenRun** [comment]
Jep, kopierede sample-db.csv til db.csv og skrev brugernavn, adgangskode og skole id ind.

**Comment by soeren-b-c** [comment]
Lige for at være helt sikker, kan du bekræfte at `db.csv` har et format som følgende:

```
school,name,pass
165,user,pass
```

hvor "user" og "pass" er dit brugernavn og kodeord?

**Comment by EsbenRun** [comment]
Jeg havde misforstået vejledningen og troet den linje med `school,name,pass` i db.csv skulle erstattes med værdierne, så det hele virker nu hvor jeg har tilføjet det igen. Undskyld fejltagelsen og tak for hjælpen.

**Comment by soeren-b-c** [comment]
Intet problem. God fornøjelse med programmet :)
