### ISSUE TITLE
Windows: "The TOR binary must be in your PATH; exiting."

### ISSUE THREAD

**Issue by Ri-Ka** [soeren-b-c/lectio-skema-til-.ics-kalender#27]
Hej,
I'm trying to run it on windows.
everything is fine, when i run "npm start" and use a browser to visit the localhost page, all i see is

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//skema.click//Lectio//DA
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-PUBLISHED-TTL:PT15M
X-WR-CALNAME:Lectio skema
X-WR-TIMEZONE:Europe/Copenhagen

in the console i get
The TOR binary must be in your PATH; exiting.

any ideas?

**Comment by soeren-b-c** [comment]
Hi,
I'm not running the code on Windows myself, so I'm just guessing here, but off the top of my head:

- How/where did you install tor, and is the tor binary "visible" to the node script?
- Have you considered running the script under linux via the WSL https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by Ri-Ka** [comment]
Hey. I solved the problem with commenting line 17 in tor-proxy.js (await exec('which tor');)
Thank you very much.
